tasks:
  - name: Install and Run Jekyll
    init: |
      cd docs
      bundle install
    command: |
      gp synch-done jekyllstart
      cd docs
      bundle exec jekyll serve
  - name: Open Site Preview
    command: |
      gp synch-await jekyllstart 
      gp preview $(gp url 4000)/datagriff