tasks:
  - name: Install and Run Jekyll
    init: |
      cd docs
      bundle install
    command: |
      gp sync-done jekyllstart
      cd docs
      bundle exec jekyll serve
      sleep 1
  - name: Open Site Preview
    command: |
      gp sync-await jekyllstart 
      gp preview $(gp url 4000)/datagriff/