tasks:
  - name: Install trunk
    before: |
      curl https://get.trunk.io -fsSL | bash -s -- -y
      trunk upgrade
  - name: Install and Run Jekyll
    init: |
      cd docs
      bundle install
    command: |
      gp sync-done jekyllstart
      cd docs
      bundle exec jekyll serve
  - name: Open Site Preview
    command: |
      gp sync-await jekyllstart 
      sleep 1
      gp preview $(gp url 4000)/datagriff/
