version: "3.9"
services:
  spectral:
    image: stoplight/spectral:5
    command: lint /tmp/whiskey_inventory.1.oas --ruleset /tmp/.spectral.yml
    volumes:
      - ./whiskey_inventory.1.oas.yml:/tmp/whiskey_inventory.1.oas:ro
      - ./.spectral.yml:/tmp/.spectral.yml:ro

  prism:
    build:
      context: .
      dockerfile: Dockerfile
    command: mock -h 0.0.0.0 /tmp/whiskey_inventory.1.oas.yml
    volumes:
      - ./whiskey_inventory.1.oas.yml:/tmp/whiskey_inventory.1.oas.yml:ro
    ports:
      - 8080:4010 # Serve the mocked API locally as available on port 8080
    healthcheck:
      test: [CMD, curl, -f, http://localhost:4010/whiskies]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 5s

  schemathesis:
    image: schemathesis/schemathesis:stable
    depends_on:
      prism:
        condition: service_healthy
    volumes:
      - ./whiskey_inventory.1.oas.yml:/tmp/whiskey_inventory.1.oas.yml:ro
    command: >
      run
      --base-url=http://prism:4010
      /tmp/whiskey_inventory.1.oas.yml
